### ISSUE TITLE
Should we check the version of lua-resty-events?

### ISSUE THREAD

**Issue by chronolaw** [Kong/lua-resty-healthcheck#134]
In 1.6.2 there is a line:

```
local RESTY_EVENTS_VER = [[^0\.1\.\d+$]]
```
It says that the library only supports `0.1.x` version of lua-resty-events.

Is it necessary? If lua-resty-events changes the version we will get a disaster.

**Comment by nowNick** [comment]
Hmmm it looks like it was intentionally introduced by @locao in https://github.com/Kong/lua-resty-healthcheck/pull/118
I don't think there's an easy answer to this since we don't have good semver parser here. 
Kong apparently already uses lua-resty-events in version 0.2.0. Did we get anny issues? If not then I think we can change it here manually for next release? How does it sound? @chronolaw 

Latest lua-resty-events release: https://github.com/Kong/lua-resty-events/releases/tag/0.2.0
Changelog in kong that bumps up lua-resty-events to 0.2.0: https://github.com/Kong/kong/blob/release/3.4.x/CHANGELOG.md#dependencies

**Comment by locao** [comment]
When lua-resty-healthcheck started to support both lua-resty-worker-events and lua-resty-events I choose to not keep the events library requirements in the rockspec, as one of these libraries would be installed just to fulfill the requirements and would never be used. The version requirement listed in the line quoted by @chronolaw was just a way to log to lua-resty-healthcheck users that any of these modules were required and none was available.

In my opinion, from the next release on we should remove all lua-resty-worker-events support (including tests), remove this version check in the code, and go back to control all requirements using the rockspec by adding lua-resty-events to it.

What do you think @nowNick @chronolaw?

**Comment by chronolaw** [comment]
Good answer, thank you @nowNick @locao.

Now lua-resty-events is 0.2.0, but in lua-resty-healthcheck we are using the `compat` module, which's version is still `0.1.x`, so the version of lua-resty-events will not impact library.

**Comment by nowNick** [comment]
I agree @locao - if we're not using lua-resty-worker-events and we won't provide new features with this runner we should probably drop it. However it might require major version bump, am I right? A change like this I think justifies `4.x.x`?

**Comment by chronolaw** [comment]
@nowNick @locao , do we have any decision for it now?

**Comment by locao** [comment]
@chronolaw @nowNick in my opinion:
- add a lua-resty-worker-events deprecation warning to `3.x.x` HEAD.
- start a `4.x.x` branch
  - remove all lua-resty-worker-events support (including tests)
  - remove the version check in the code
  - go back to control all requirements using the rockspec by adding lua-resty-events to it.

If there are no opposing views, I can create the required tickets on our backlog.
